services:
  postgres:
    image: postgres:latest
    container_name: postgres-test-task
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - postgres-test-task_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-test-task
    ports:
      - '6379:6379'
    volumes:
      - redis-test-task_data:/data

volumes:
  postgres-test-task_data:
  redis-test-task_data: